name: Runs darglint tox job
on:
  schedule:
    - cron: '01 17 * * *'  # Each day at 01:17 UTC,
  push:  # TODO: remove before merge to wandb/client
jobs:
  darglint:  # run our tox darglint job.
    runs-on: ubuntu-latest
    steps:
      - name: checkout client repo
        uses: actions/checkout@v2
        with:
          repository: charlesfrye/client  # TODO: change before merge to wandb/client
          persist-credentials: false
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: setup tox
        run: python -m pip install tox
      - name: run darglint
        run: tox -e darglint wandb/__init__.py wandb/apis/public.py wandb/data_types.py wandb/integration/keras/__init__.py wandb/integration/keras/keras.py wandb/sdk/data_types.py wandb/sdk/wandb_artifacts.py wandb/sdk/wandb_config.py wandb/sdk/wandb_init.py wandb/sdk/wandb_run.py wandb/sdk/wandb_summary.py wandb/sdk/wandb_sweep.py wandb/sdk/wandb_watch.py wandb/wandb_agent.py
